spring.application.name=senai-notes


spring.datasource.url=jdbc:postgresql://banco-senainotes.c7aspmhndgf0.us-east-1.rds.amazonaws.com/postgres
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_schema=notes
